version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: nodex_neo4j_v3  # Renamed container
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/yourStrongPassword
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

  backend:
    build: ./backend
    container_name: nodex_backend_v3  # Renamed container
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/sample_data.json:/app/sample_data.json
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://nodex_neo4j_v3:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=yourStrongPassword
      - JWT_SECRET_KEY=tu_super_secreto_jwt
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  frontend:
    build: ./frontend
    container_name: nodex_frontend_v3  # Renamed container
    ports:
      - "0.0.0.0:4545:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=4545
      - WDS_SOCKET_PATH=/ws

volumes:
  neo4j_data:
